import com.prachi.sample.simpleDrool.Customer;

rule "Customer is a NEW Customer With Birthday as Today"
    when
        offerIs: Customer(newCustomer && customerBirthDayToday && totalSpending >= 100 )
    then
        offerIs.setDiscount(20);
        System.out.println("Rule1");
     end

rule "Customer is a Existing Customer"
    when
        offerIs: Customer(!newCustomer)
    then
        offerIs.setDiscount(10);
        System.out.println("Rule2");
     end

rule "Customer is a NEW Customer and not BD as today"
    when
        offerIs: Customer(newCustomer && !customerBirthDayToday)
    then
        offerIs.setDiscount(10);
        System.out.println("Rule3");
     end

rule "Customer is a NEW Customer With Birthday as Today but spending less than 100"
    when
        offerIs: Customer(newCustomer && customerBirthDayToday && totalSpending<100)
    then
        offerIs.setDiscount(10);
        System.out.printf("Rule 4");
     end
